1-setup/docker-setup/adminer-gui/docker-compose.yml
1-setup/docker-setup/docker-compose.yml
1-setup/docker-setup/mysql/Dockerfile
1-setup/docker-setup/mysql/docker-compose.yml
1-setup/docker-setup/postgresql/Dockerfile
1-setup/docker-setup/postgresql/docker-compose.yml
1-setup/docker-setup/sqlserver/Dockerfile
1-setup/docker-setup/sqlserver/docker-compose.yml
1-setup/schema/university-sqlserver.sql
README.md

Relates to https://github.com/Baeldung/sql-tutorials/issues/8
**Question**: Should it be PG 14 or 16?
- Refer to README to the instructions

Created the docker setup for databases

---

sql-queries/README.md

Updated the relevant articles on README.md for UX-14949

Update on README.md

---

sql-queries/having-vs-where/having-clause-example.sql
sql-queries/having-vs-where/where-clause-example.sql

SQL-106: Difference between HAVING and WHERE in SQL

---

sql-queries-3/delete-select-where/MySQL Alias.sql
sql-queries-3/delete-select-where/MySQL Temporary Table.sql
sql-queries-3/delete-select-where/PostgreSQL.sql
sql-queries-3/delete-select-where/SQL Server.sql
sql-queries-3/delete-select-where/createdir.txt

https://jira.baeldung.com/browse/SQL-137

https://jira.baeldung.com/browse/SQL-137

---

sql-queries-3/README.md
sql-queries-3/sql-ignore-index/mysql-analyze-query-plan.sql
sql-queries-3/sql-ignore-index/mysql-ignore-index-IGNORE-INDEX-hint.sql
sql-queries-3/sql-ignore-index/mysql-ignore-index-USE-INDEX-hint.sql
sql-queries-3/sql-ignore-index/mysql-ignore-index-for-group-by.sql
sql-queries-3/sql-ignore-index/mysql-ignore-index-for-join.sql
sql-queries-3/sql-ignore-index/mysql-ignore-index-for-order-by.sql
sql-queries-3/sql-ignore-index/mysql-optimizer-hint-no-index.sql
sql-queries-3/sql-ignore-index/mysql-show-indexes.sql
sql-queries-3/sql-ignore-index/sql-server-WITH-clause.sql
sql-queries-3/sql-ignore-index/sql-server-ignore-index-by-exclusion.sql
sql-queries-3/sql-ignore-index/sql-server-ignore-index-hint.sql
sql-queries-3/sql-ignore-index/sql-server-setup.sql

I created a new module in `sql-tutorials` called` sql-queries-3`. Added a new sub-module in `sql-queries-3` called `sql-ignore-index`. Added a `README.md` file to the sub-module. Added 12 SQL scripts to `sql-ignore-index`. Added a link to article in `REDME.md` which may need to be modified if draft. 
Deepak Vohra

SQL scripts for article How to Ignore an Index From Being Used in SQL

---

sql-queries-2/delete-inner-join/delete-row-inner-join-alias.sql
sql-queries-2/delete-inner-join/delete-row-inner-join.sql
sql-queries-2/delete-orphan-records/delete-orphan-records-left-join.sql
sql-queries-2/delete-orphan-records/delete-orphan-records-not-exists.sql
sql-queries-2/delete-orphan-records/delete-orphan-records-not-in.sql
sql-queries-2/delete-orphan-records/identify-orphan-records.sql
sql-queries-2/select-date-without-time/cast()-function.sql
sql-queries-2/select-date-without-time/date()-function.sql
sql-queries-2/select-date-without-time/date-format()-function.sql

Reverts Baeldung/sql-tutorials#70

Revert "delete-inner-join"

---

sql-queries/sql-text-search/pattern_matching.sql

Removed inserts and cleaned the scripts to just use sql queries

 SQL-76:Pattern matching functions in MySQL

---

sql-queries-3/drop-table-if-exists/script-ms-sql.sql
sql-queries-3/drop-table-if-exists/script-mysql.sql
sql-queries-3/drop-table-if-exists/script-postgresql.sql

DROP TABLE IF EXISTS

---

sql-queries-4/trimming-strings-sql/Create-ventures-schema.sql
sql-queries-4/trimming-strings-sql/apply-trim-function-columns.sql
sql-queries-4/trimming-strings-sql/using-LTRIM.sql
sql-queries-4/trimming-strings-sql/using-RTRIM.sql
sql-queries-4/trimming-strings-sql/using-TRIM.sql

Trimming Strings in SQL

---

sql-queries-4/which-sql-require-commit-mysql/create-temporary-table.sql
sql-queries-4/which-sql-require-commit-mysql/delete.sql
sql-queries-4/which-sql-require-commit-mysql/insert.sql
sql-queries-4/which-sql-require-commit-mysql/replace.sql
sql-queries-4/which-sql-require-commit-mysql/select.sql
sql-queries-4/which-sql-require-commit-mysql/update.sql

Added new sub-repo _sql-tutorials/sql-queries-4/which-sql-require-commit-mysql_

Which SQL Statements Require a Commit in MySQL

---

sql-queries-4/store-decimal-values/create-order-schema.sql
sql-queries-4/store-decimal-values/insert-value-within-decimal-range.sql
sql-queries-4/store-decimal-values/value-exceed-total-digit-integer.sql
sql-queries-4/store-decimal-values/values-exceeding-decimal-scale.sql

How to Store Decimal Values in SQL

How to Store Decimal Values in SQL

---

sql-queries-5/difference_between_CTE_and_Subquery/correlated_subquery.sql
sql-queries-5/difference_between_CTE_and_Subquery/cte_use_case.sql
sql-queries-5/difference_between_CTE_and_Subquery/multi_row_subquery.sql
sql-queries-5/difference_between_CTE_and_Subquery/recursive_cte_query.sql
sql-queries-5/difference_between_CTE_and_Subquery/scalar_subquery.sql
sql-queries-5/difference_between_CTE_and_Subquery/subquery_use_case.sql

Difference Between CTE and Subquery

Difference Between CTE and Subquery

---

sql-queries-4/README.md

Adding relevant articles on README.md for UX-17498

sql-queries-4

---

sql-queries-3/README.md

Adding relevant articles on README.md for UX-17498

sql-queries-3

---

sql-queries-dates/README.md

Adding relevant articles on README.md for UX-17498

group-by-date-parts

---

sql-queries-like/equals-vs-like/Equals (=) String Comparison.sql
sql-queries-like/equals-vs-like/Equals (=) With Date and Time Data.sql
sql-queries-like/equals-vs-like/Equals (=) With Numeric Data.sql
sql-queries-like/equals-vs-like/LIKE Wildcard Characters.sql
sql-queries-like/equals-vs-like/LIKE vs. Equals (=).sql

https://jira.baeldung.com/browse/SQL-374

https://jira.baeldung.com/browse/SQL-374

---

1-setup/docker-setup/README.md
1-setup/docker-setup/sqlserver/docker-compose.yml

Change due to SQL Server tools path change (https://github.com/microsoft/mssql-docker/issues/892)

Fix for the Docker issue for SQL Server

---

sql-queries-7/Sort-by-a-List-of-Strings-in-SQL/Sort-by-a-strings-of-list-in-MySQL.sql
sql-queries-7/Sort-by-a-List-of-Strings-in-SQL/Sort-by-a-strings-of-list-in-PostgreSQL.sql
sql-queries-7/Sort-by-a-List-of-Strings-in-SQL/Sort-by-a-strings-of-list-in-SQL-Server.sql

sort by a list of string in MySQL, SQL Server, and PostgreSQL

Sort by a list of strings in SQL

---

sql-queries-8/escape-single-quote/escape-single-quote-mssql.sql
sql-queries-8/escape-single-quote/escape-single-quote-mysql.sql
sql-queries-8/escape-single-quote/escape-single-quote-psql.sql

SQL-91 | How to escape a single quote in SQL Server?

SQL-91 | How to escape a single quote in SQL Server?

---

sql-subqueries/subquery-vs-correlated-subquery/correlated subquery.sql
sql-subqueries/subquery-vs-correlated-subquery/subquery.sql

A folder containing the SQL query examples for subquery and correlated subqueries was created. For Baeldung SQL article issue sql-245.

subquery and correlated subquery

---

sql-queries-11/sum-distinct-rows/distinct-within-subquery.sql
sql-queries-11/sum-distinct-rows/sum-with-cte.sql
sql-queries-11/sum-distinct-rows/union-within-subquery.sql

The code for the SQL 446. The SQL commands from each section has been separated into different files.

SQL-446: How to SUM DISTINCT Rows in SQL
